import {test} from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {chromium} from 'playwright';
test('separate agent page has scoped tabs, defaults, offline warning, safe drafts and clear actions',{timeout:20000},async()=>{
 const app=express();app.use(express.json());let online=false,fail=false,calls=[],config={commandOwnerId:'123456789012345680'},id='550e8400-e29b-41d4-a716-446655440000';app.get('/api/config',(_q,r)=>r.json({auth:{mode:'fixture'}}));app.get('/api/state',(_q,r)=>r.json({swarms:[{id,bots:[{name:'Semi'}],config}]}));app.get('/api/relays/:id/commands',(_q,r)=>r.json({bridge:online?'online':'offline',collector:'waiting',commands:[]}));app.patch('/api/relays/:id/chat',(q,r)=>{calls.push({url:q.url,body:q.body});if(fail)return r.status(500).json({error:'Private failure'});config={...config,chat:q.body.chat,personality:q.body.personality};r.json({status:'saved'});});app.patch('/api/relays/:id/limits',(q,r)=>{calls.push({url:q.url,body:q.body});config={...config,chat:{...config.chat,maxRepliesPerHour:q.body.maxRepliesPerHour},commands:q.body.commands};r.json({status:'saved'});});app.use(express.static('frontend'));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));server.requestTimeout=5000;const browser=await chromium.launch({headless:true});
 try{const page=await browser.newPage();await page.route('**/auth.js',r=>r.fulfill({contentType:'text/javascript',body:`export async function initAuth(c,h){document.querySelector('#signed-in').hidden=false;document.querySelector('#signed-out').hidden=true;h.onLogin();return {getUser:()=>({}),getValidToken:async()=>'synthetic'};}`}));const origin=`http://127.0.0.1:${server.address().port}`;await page.goto(origin+'/agent.html?relay='+id,{timeout:10000});await page.locator('#chat-personality').waitFor();assert.equal(await page.locator('dialog').isVisible(),false);assert.equal(await page.locator('#chat-mode').inputValue(),'normal');assert.match(await page.locator('#chat-personality').inputValue(),/friendly, curious/);assert.ok((await page.locator('#chat-personality').boundingBox()).height>=180);await page.locator('.runtime-warning').waitFor();assert.match(await page.locator('.runtime-warning').textContent(),/⚠ Runtime bridge offline/);assert.equal(await page.getByText('From your Discord command user:',{exact:false}).isVisible(),false);assert.equal(await page.locator('#command-authorizedUserId,#command-pollSeconds,#chat-cooldownSeconds').count(),0);const buttons=await page.locator('.agent-actions button').all();const a=await buttons[0].boundingBox(),b=await buttons[1].boundingBox();assert.ok(b.y>=a.y+a.height+8||b.x>=a.x+a.width+8);
 await page.locator('#chat-personality').fill('Keep my unsaved personality');await page.locator('#chat-mode').selectOption('off');await page.getByRole('tab',{name:'Limits',exact:true}).click();await page.locator('#chat-maxRepliesPerHour').fill('12');await page.locator('#command-dailyRuntimeMinutes').fill('20');await page.locator('#command-enabled').check();online=true;await page.getByRole('button',{name:'Save limits',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Limits saved.');assert.equal(calls[0].body.maxRepliesPerHour,12);assert.equal(calls[0].body.commands.dailyRuntimeMinutes,20);assert.equal(calls[0].body.commands.authorizedUserId,undefined);assert.equal(calls[0].body.commands.pollSeconds,undefined);assert.equal(await page.getByText('From your Discord command user:',{exact:false}).isVisible(),true);
 await page.getByRole('tab',{name:'Personality',exact:true}).click();assert.equal(await page.locator('#chat-personality').inputValue(),'Keep my unsaved personality');await page.getByRole('button',{name:'Save chat settings',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Chat settings saved.');assert.deepEqual(calls.at(-1).body.chat,{mode:'off',cooldownSeconds:0,maxRepliesPerHour:12});fail=true;await page.locator('#chat-personality').fill('Preserve on failure');await page.getByRole('button',{name:'Save chat settings',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Server temporarily unavailable'));assert.equal(await page.locator('#chat-personality').inputValue(),'Preserve on failure');assert.equal(await page.getByRole('button',{name:'Save chat settings',exact:true}).isEnabled(),true);
 for(const colorScheme of ['light','dark']){await page.emulateMedia({colorScheme});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const colors=await page.locator('#chat-personality').evaluate(n=>[getComputedStyle(n).color,getComputedStyle(n).backgroundColor]);assert.notEqual(...colors);}
 await page.goto(origin+'/agent.html?relay=11111111-1111-4111-8111-111111111111',{timeout:10000});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('not available to your signed-in account'));assert.equal(await page.locator('#chat-personality').count(),0);
 online=false;await page.goto(origin+'/agent.html?relay='+id,{timeout:10000});await page.getByRole('button',{name:'⚠ Runtime bridge offline',exact:true}).click();await page.getByRole('dialog',{name:'Runtime bridge setup'}).waitFor();const preview=await page.locator('dialog pre').innerText();assert.ok(preview.includes(id));await page.evaluate(()=>{window.copiedPrompt=null;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedPrompt=text;}}});});await page.getByRole('button',{name:'Copy runtime bridge setup prompt',exact:true}).click();await page.getByText('Copied!',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.copiedPrompt),preview);await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Show runtime bridge setup prompt',exact:true}).click();await page.getByRole('dialog',{name:'Runtime bridge setup'}).waitFor();assert.equal(await page.locator('dialog pre').innerText(),preview);
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
});
