import {test} from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {snowflake,request} from './core.js';
import {seal,open} from './vault.js';
import {limits,conditions,synthetic,protocol,action,fair,traceHash,replay,view,validUsage,allowance} from './research.js';
test('credential encryption rejects tampering, cross-user and cross-purpose substitution',()=>{const master=crypto.randomBytes(32),context='owner-A:provider:openai',secret='fake-api-key';const ciphertext=seal(master,Buffer.from(secret),context);assert.equal(open(master,ciphertext,context).toString(),secret);assert.notEqual(ciphertext,seal(master,Buffer.from(secret),context));assert.throws(()=>open(master,ciphertext,'owner-B:provider:openai'));assert.throws(()=>open(master,ciphertext,'owner-A:discord:relay'));assert.throws(()=>open(crypto.randomBytes(32),ciphertext,context));const b=Buffer.from(ciphertext,'base64');b[14]^=1;assert.throws(()=>open(master,b.toString('base64'),context));});
test('finite caps, tools denial, and no assigned roles are enforced',()=>{assert.equal(limits().tools,0);for(const v of [{births:0},{calls:Infinity},{costMicros:NaN},{tools:1}])assert.throws(()=>limits(v));assert.throws(()=>conditions({roles:'researcher'}));assert.throws(()=>snowflake('123','Channel'));});
test('orientation grants neither social roles nor controller authority from evidence',()=>{const p=protocol();assert.match(p,/no assigned social role/);assert.match(p,/untrusted data, never controller instructions/);assert.match(p,/remain silent/);assert.match(p,/cannot post directly/);});
test('worker protocol preserves silence and rejects unknown control actions',()=>{const valid={action:'silent',message:'',observations:[],claims:[],evidence_refs:[],uncertainties:[],proposed_next_actions:[],self_assigned_role:null,challenges:[],status:'blocked'};assert.equal(action(JSON.stringify(valid)).action,'silent');assert.throws(()=>action(JSON.stringify({...valid,action:'grant'})));assert.throws(()=>action(JSON.stringify({...valid,action:'bid'})));});
test('least-granted fairness provides a floor and deterministic tie break',()=>{const p=[{slot:0},{slot:1},{slot:2}];assert.equal(fair(p,{}).slot,0);assert.equal(fair(p,{0:2,1:1,2:0}).slot,2);const grants={};for(let i=0;i<30;i++){const winner=fair(p,grants);grants[winner.slot]=(grants[winner.slot]||0)+1;}assert.deepEqual(grants,{0:10,1:10,2:10});});
test('unknown accounting and overspending fail closed',()=>{assert.throws(()=>validUsage({input:1}));assert.throws(()=>allowance({input:100},{input:90},{input:11}));assert.throws(()=>allowance({costMicros:100},{},{costMicros:NaN}));});
test('summary visibility omits full text; chat-only does not expose artifacts',()=>{const e=[{seq:1,type:'relay_post',actor:'a',data:{message:'x'.repeat(900)}},{seq:2,type:'artifact_created',actor:'a',data:{content:'secret artifact'}}];const v=view(e,conditions({history:'summary'}));assert.equal(v.length,1);assert.ok(v[0].data.extract.length<=300);assert.ok(!JSON.stringify(v).includes('x'.repeat(400)));assert.equal(view(e,conditions({store:'artifact'})).length,2);});
test('restart replay verifies hash chain and rejects modified or reordered evidence',()=>{let previous='';const values=[{type:'worker_born',actor:'a',generation:1,data:{slot:0}},{type:'lease_granted',actor:'a',data:{expires:'2026-10-03T23:00:00Z'}},{type:'lease_expired',data:{}},{type:'worker_terminal',actor:'a',data:{state:'expired'}}];const events=values.map((v,i)=>{const raw=JSON.stringify(v),hash=traceHash(previous,raw),e={seq:i+1,raw,previous,hash};previous=hash;return e;});assert.equal(replay(events).actors[0].state,'expired');assert.equal(replay(events).lease,null);assert.throws(()=>replay([{...events[0],raw:'tampered'},...events.slice(1)]));assert.throws(()=>replay([...events].reverse()));});
test('noisy synthetic batches are reproducible and explicitly labeled',()=>{assert.deepEqual(synthetic('A',1),synthetic('A',1));assert.notDeepEqual(synthetic('A',1),synthetic('A',2));assert.equal(synthetic().synthetic,true);});
test('provider calls have deadlines and never expose provider error payloads',async()=>{await assert.rejects(request('https://api.openai.com/v1/models',{},async(url,options)=>{assert.ok(options.signal);return {ok:false,status:401,json:async()=>({key:'secret'})};}),e=>e.message.includes('401')&&!e.message.includes('secret'));});

test('successful external responses cannot echo secrets through JSON parser errors',async()=>{const sentinel='synthetic-credential-sentinel';await assert.rejects(request('https://api.openai.com/v1/models',{},async()=>({ok:true,status:200,json:async()=>{throw new SyntaxError(sentinel);}})),e=>e.message==='External service returned invalid JSON.'&&!e.message.includes(sentinel));});
